import sqlite3
import datetime
import os

conn = sqlite3.connect('nepms_local.db')
cursor = conn.cursor()
cursor.execute('SELECT name FROM sqlite_master WHERE type=\'table\'')
tables = [row[0] for row in cursor.fetchall()]

# Filter out non-application tables
tables = [t for t in tables if t not in ('alembic_version', 'sqlite_sequence')]

# Make sure we add staff_roles if not present, because Supabase uses it
if 'staff_roles' not in tables:
    tables.append('staff_roles')

# We'll create a new migration file
timestamp = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
filename = f'../supabase/migrations/{timestamp}_multi_tenant_rls_policies.sql'

with open(filename, 'w') as f:
    f.write('-- Migration: Apply Multi-Tenant RLS Policies across all tables\n')
    f.write('-- Autogenerated\n\n')
    
    # 1. Helper functions
    f.write('-- 1. Check if the current user is a Super Admin\n')
    f.write('CREATE OR REPLACE FUNCTION current_user_is_super_admin()\n')
    f.write('RETURNS boolean AS $$\n')
    f.write('BEGIN\n')
    f.write('  RETURN EXISTS (\n')
    f.write('    SELECT 1 FROM super_admins \n')
    f.write('    WHERE auth_user_id = auth.uid() AND is_active = true\n')
    f.write('  );\n')
    f.write('END;\n')
    f.write('$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;\n\n')
    
    f.write('-- 2. Get the Pharmacy ID for the current user\n')
    f.write('CREATE OR REPLACE FUNCTION current_user_pharmacy_id()\n')
    f.write('RETURNS uuid AS $$\n')
    f.write('BEGIN\n')
    f.write('  RETURN (\n')
    f.write('    SELECT pharmacy_id FROM staff_roles \n')
    f.write('    WHERE user_id = auth.uid() \n')
    f.write('    LIMIT 1\n')
    f.write('  );\n')
    f.write('END;\n')
    f.write('$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;\n\n')

    # 2. Policies
    for table in tables:
        f.write(f'-- ==========================================\n')
        f.write(f'-- Policies for table: {table}\n')
        f.write(f'-- ==========================================\n')
        f.write(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;\n\n')
        
        if table == 'staff_roles':
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (ALL)" ON {table}\n')
            f.write(f'FOR ALL TO authenticated\n')
            f.write(f'USING (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR user_id = auth.uid()\n')
            f.write(f'    OR pharmacy_id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (INSERT)" ON {table}\n')
            f.write(f'FOR INSERT TO authenticated\n')
            f.write(f'WITH CHECK (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR pharmacy_id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')
            
        elif table == 'super_admins':
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (ALL)" ON {table}\n')
            f.write(f'FOR ALL TO authenticated\n')
            f.write(f'USING (current_user_is_super_admin());\n\n')
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (INSERT)" ON {table}\n')
            f.write(f'FOR INSERT TO authenticated\n')
            f.write(f'WITH CHECK (current_user_is_super_admin());\n\n')
            
        elif table == 'pharmacies':
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (ALL)" ON {table}\n')
            f.write(f'FOR ALL TO authenticated\n')
            f.write(f'USING (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (INSERT)" ON {table}\n')
            f.write(f'FOR INSERT TO authenticated\n')
            f.write(f'WITH CHECK (\n')
            f.write(f'    current_user_is_super_admin()\n')
            f.write(f');\n\n')
            
        elif table in ('audit_events', 'audit_log_chain', 'camera_snapshots'):
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (SELECT)" ON {table}\n')
            f.write(f'FOR SELECT TO authenticated\n')
            f.write(f'USING (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR pharmacy_id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')
            
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (INSERT)" ON {table}\n')
            f.write(f'FOR INSERT TO authenticated\n')
            f.write(f'WITH CHECK (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR pharmacy_id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')
            
        else:
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (ALL)" ON {table}\n')
            f.write(f'FOR ALL TO authenticated\n')
            f.write(f'USING (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR pharmacy_id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')
            
            f.write(f'CREATE POLICY "Pharmacy isolation for {table} (INSERT)" ON {table}\n')
            f.write(f'FOR INSERT TO authenticated\n')
            f.write(f'WITH CHECK (\n')
            f.write(f'    current_user_is_super_admin() \n')
            f.write(f'    OR pharmacy_id = current_user_pharmacy_id()\n')
            f.write(f');\n\n')

print(f'Generated {filename} with {len(tables)} tables.')
