"""purchase_updates

Revision ID: 1e78194f4baa
Revises: f0eec2f4f201
Create Date: 2026-06-20 16:36:50.024543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e78194f4baa'
down_revision: Union[str, Sequence[str], None] = 'f0eec2f4f201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_ledger',
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_ledger_id'), 'supplier_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_ledger_is_deleted'), 'supplier_ledger', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_supplier_ledger_tenant_id'), 'supplier_ledger', ['tenant_id'], unique=False)
    op.create_table('purchase_returns',
    sa.Column('return_number', sa.String(length=100), nullable=True),
    sa.Column('grn_id', sa.String(length=36), nullable=True),
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_returns_id'), 'purchase_returns', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_returns_is_deleted'), 'purchase_returns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_purchase_returns_return_number'), 'purchase_returns', ['return_number'], unique=True)
    op.create_index(op.f('ix_purchase_returns_tenant_id'), 'purchase_returns', ['tenant_id'], unique=False)
    op.create_table('supplier_payments',
    sa.Column('supplier_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['purchase_invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_payments_id'), 'supplier_payments', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_payments_is_deleted'), 'supplier_payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_supplier_payments_tenant_id'), 'supplier_payments', ['tenant_id'], unique=False)
    op.add_column('suppliers', sa.Column('current_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'current_balance')
    op.drop_index(op.f('ix_supplier_payments_tenant_id'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_is_deleted'), table_name='supplier_payments')
    op.drop_index(op.f('ix_supplier_payments_id'), table_name='supplier_payments')
    op.drop_table('supplier_payments')
    op.drop_index(op.f('ix_purchase_returns_tenant_id'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_return_number'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_is_deleted'), table_name='purchase_returns')
    op.drop_index(op.f('ix_purchase_returns_id'), table_name='purchase_returns')
    op.drop_table('purchase_returns')
    op.drop_index(op.f('ix_supplier_ledger_tenant_id'), table_name='supplier_ledger')
    op.drop_index(op.f('ix_supplier_ledger_is_deleted'), table_name='supplier_ledger')
    op.drop_index(op.f('ix_supplier_ledger_id'), table_name='supplier_ledger')
    op.drop_table('supplier_ledger')
    # ### end Alembic commands ###
