"""Add purchase returns

Revision ID: 22a9cf58e3ed
Revises: 21fe568d7732
Create Date: 2026-07-08 18:22:43.092134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a9cf58e3ed'
down_revision: Union[str, Sequence[str], None] = '21fe568d7732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_return_items',
    sa.Column('purchase_return_id', sa.String(length=36), nullable=True),
    sa.Column('medicine_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_returned', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_return_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('po_id', sa.String(length=36), nullable=True))
        # Naming the constraint explicitly to avoid SQLite error
        batch_op.create_foreign_key('fk_purchase_returns_po_id', 'purchase_orders', ['po_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_returns_po_id', type_='foreignkey')
        batch_op.drop_column('po_id')

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_id'))

    op.drop_table('purchase_return_items')
    # ### end Alembic commands ###
