"""phase_7_accounts

Revision ID: 37cada3371bd
Revises: 6001_phase_6_sales
Create Date: 2026-07-15 15:29:58.785650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cada3371bd'
down_revision: Union[str, Sequence[str], None] = '6001_phase_6_sales'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('account_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_accounts_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_accounts_parent_id_accounts'), 'accounts', ['parent_id'], ['id'])

    with op.batch_alter_table('advance_salaries', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('alert_config', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_alert_config_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_alert_history_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_events_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('audit_items', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_items_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('audit_sessions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_sessions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('backup_history', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bank_accounts_account_id'), ['account_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_bank_accounts_account_number'), ['account_number'])

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_batches_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('branch_devices', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_branch_devices_mac_address'), ['mac_address'])

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_branches_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('camera_snapshots', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_camera_snapshots_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('cash_ledger_entries', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_cash_ledger_entries_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_cash_ledger_entries_journal_entry_id_journal_entries'), 'journal_entries', ['journal_entry_id'], ['id'])

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawer_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_cash_sessions_drawer_id'), ['drawer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sessions_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_cash_sessions_drawer_id_cash_drawers'), 'cash_drawers', ['drawer_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_categories_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_customer_ledger_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_customer_payments_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(batch_op.f('fk_departments_head_id_employees'), 'employees', ['head_id'], ['id'])
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('designations', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(batch_op.f('fk_designations_department_id_departments'), 'departments', ['department_id'], ['id'])
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_username'), ['username'], unique=True)
        pass
        batch_op.create_foreign_key(batch_op.f('fk_employees_shift_id_shifts'), 'shifts', ['shift_id'], ['id'])
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('journal_entry_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('bank_account_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_expense_vouchers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_vouchers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_vouchers_pharmacy_id'), ['pharmacy_id'], unique=False)
        pass
        batch_op.create_foreign_key(batch_op.f('fk_expense_vouchers_journal_entry_id_journal_entries'), 'journal_entries', ['journal_entry_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_expense_vouchers_approved_by_users'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_expense_vouchers_bank_account_id_bank_accounts'), 'bank_accounts', ['bank_account_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_expense_vouchers_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('grns', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_grns_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_holidays_tenant_id'), ['tenant_id'], unique=False)
        pass
        batch_op.create_foreign_key(batch_op.f('fk_holidays_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('inventory_cycle_count_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_cycle_count_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_cycle_count_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_cycle_count_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_cycle_count_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_inventory_cycle_count_items_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('inventory_cycle_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_cycle_counts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_cycle_counts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_cycle_counts_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_cycle_counts_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_inventory_cycle_counts_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('inventory_reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_reservations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_reservations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_inventory_reservations_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('invoice_settings', schema=None) as batch_op:
        pass
        batch_op.drop_column('show_payment_method')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('source_module', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_journal_entries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('warehouse_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_journal_entry_lines_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_journal_entry_lines_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_age_groups', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_age_groups_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_bins', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_bins_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_brands', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_brands_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_categories', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_categories_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_dosage_forms', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_dosage_forms_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_flavors', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_flavors_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_generics', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_generics_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_manufacturers', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_manufacturers_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_packaging', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_packaging_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_prescription_types', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_prescription_types_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_racks', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_racks_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_routes', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_routes_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_shelves', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_shelves_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_storage_conditions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_storage_conditions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_strength_units', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_strength_units_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_strengths', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_strengths_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_suppliers', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_suppliers_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_tax_rules', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_tax_rules_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_units', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_units_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('master_warehouses', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_warehouses_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_ai_tags', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_ai_tags_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_audit_logs_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_barcodes', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_barcodes_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_conversion_rules', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_conversion_rules_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_custom_fields', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_custom_fields_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_documents', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_documents_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_images', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_images_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_master', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_master_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_packaging', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_packaging_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_pricing', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_pricing_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_medicine_pricing_medicine_id'), ['medicine_id'])

    with op.batch_alter_table('medicine_substitutes', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('medicine_supplier_mapping', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_supplier_mapping_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicine_templates', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_templates_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_medicine_templates_name'), ['name'])

    with op.batch_alter_table('medicine_versions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicine_versions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_medicines_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('ocr_queues', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('packaging_levels', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_packaging_levels_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_index(batch_op.f('ix_payment_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_payment_transactions_gateway_transaction_id'), ['gateway_transaction_id'])

    with op.batch_alter_table('payroll_lines', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        pass
        batch_op.create_foreign_key(batch_op.f('fk_payroll_runs_approved_by_users'), 'users', ['approved_by'], ['id'])
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_payroll_settings_employee_id'), ['employee_id'])
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_permissions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('petty_cash_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_petty_cash_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_petty_cash_categories_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_petty_cash_categories_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_petty_cash_categories_tenant_id'), ['tenant_id'], unique=False)
        pass
        batch_op.create_foreign_key(batch_op.f('fk_petty_cash_categories_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacies_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_pharmacies_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_pharmacies_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('pharmacy_subscriptions', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_index(batch_op.f('ix_pharmacy_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_subscriptions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_pharmacy_subscriptions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_pharmacy_subscriptions_pharmacy_id'), ['pharmacy_id'])

    with op.batch_alter_table('po_items', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_po_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_po_items_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_prescription_items_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_prescriptions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_purchase_invoices_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_approved_by_users'), 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_purchase_return_items_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_purchase_returns_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_purchase_returns_po_id_purchase_orders'), 'purchase_orders', ['po_id'], ['id'])

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_role_permissions_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_roles_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sale_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sale_items_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('sale_return_items', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sale_return_items_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sale_returns_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sales_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_coupon_id_coupons'), 'coupons', ['coupon_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_promotion_id_promotion_campaigns'), 'promotion_campaigns', ['promotion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_journal_entry_id_journal_entries'), 'journal_entries', ['journal_entry_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_salesperson_id_users'), 'users', ['salesperson_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_shift_id_cash_sessions'), 'cash_sessions', ['shift_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_counter_id_branch_counters'), 'branch_counters', ['counter_id'], ['id'])

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_stock_adjustments_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_stock_movements_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_transfer_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_items_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_stock_transfer_items_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_stock_transfers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfers_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfers_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfers_reference_no'), ['reference_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_transfers_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_stock_transfers_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_index(batch_op.f('ix_subscription_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_subscription_plans_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('super_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_super_admins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_super_admins_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_super_admins_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_super_admins_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_super_admins_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('supplier_contracts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_supplier_contracts_contract_number'), ['contract_number'])

    with op.batch_alter_table('supplier_ledger', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_supplier_ledger_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('supplier_medicine_prices', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_supplier_medicine_prices_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_supplier_payments_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_suppliers_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('system_modules', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        pass
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_tenants_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('user_branches', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_branches_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_pharmacy_id'), ['pharmacy_id'], unique=False)

    with op.batch_alter_table('warehouse_bins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_warehouse_bins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_bins_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_bins_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_bins_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_warehouse_bins_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('warehouse_racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('sync_version', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_warehouse_racks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_racks_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_racks_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_racks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_warehouse_racks_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('whatsapp_bot_log', schema=None) as batch_op:
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_whatsapp_bot_log_pharmacy_id'), ['pharmacy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_bot_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_bot_log_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('warehouse_racks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_warehouse_racks_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_warehouse_racks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_racks_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_racks_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_warehouse_racks_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('warehouse_bins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_warehouse_bins_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_warehouse_bins_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_bins_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_bins_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_warehouse_bins_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('user_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_branches_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('system_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_payments_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('supplier_medicine_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_medicine_prices_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('supplier_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_ledger_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('supplier_contracts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_supplier_contracts_contract_number'), type_='unique')

    with op.batch_alter_table('super_admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_super_admins_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_super_admins_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_super_admins_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_super_admins_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_super_admins_id'))

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subscription_plans_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_subscription_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_id'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_transfers_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_transfers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfers_reference_no'))
        batch_op.drop_index(batch_op.f('ix_stock_transfers_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_transfers_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('stock_transfer_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_transfer_items_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_transfer_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_items_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_items_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_counter_id_branch_counters'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_shift_id_cash_sessions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_salesperson_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_journal_entry_id_journal_entries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_promotion_id_promotion_campaigns'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_coupon_id_coupons'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_returns_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('sale_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_return_items_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_items_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sale_items_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_returns_po_id_purchase_orders'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_returns_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_return_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_return_items_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_approved_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_items_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('po_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_po_items_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_po_items_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('pharmacy_subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pharmacy_subscriptions_pharmacy_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_pharmacy_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_subscriptions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_pharmacy_subscriptions_id'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pharmacies_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_pharmacies_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pharmacies_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_pharmacies_id'))

    with op.batch_alter_table('petty_cash_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_petty_cash_categories_branch_id_branches'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_petty_cash_categories_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_petty_cash_categories_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_petty_cash_categories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_petty_cash_categories_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('sync_version')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_payroll_settings_employee_id'), type_='unique')

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_payroll_runs_approved_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('payroll_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_payment_transactions_gateway_transaction_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_payment_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_id'))
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('packaging_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packaging_levels_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('ocr_queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicines_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_versions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_medicine_templates_name'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_medicine_templates_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_supplier_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_supplier_mapping_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_substitutes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('medicine_pricing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_medicine_pricing_medicine_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_medicine_pricing_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_packaging', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_packaging_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_master_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_images_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_documents_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_custom_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_custom_fields_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_conversion_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_conversion_rules_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_barcodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_barcodes_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_audit_logs_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('medicine_ai_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medicine_ai_tags_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_warehouses_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_units_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_tax_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_tax_rules_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_suppliers_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_strengths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_strengths_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_strength_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_strength_units_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_storage_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_storage_conditions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_shelves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_shelves_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_routes_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_racks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_racks_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_prescription_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_prescription_types_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_packaging', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_packaging_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_manufacturers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_manufacturers_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_generics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_generics_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_flavors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_flavors_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_dosage_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_dosage_forms_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_categories_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_brands_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_bins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_bins_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('master_age_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_age_groups_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entry_lines_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entry_lines_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('sync_version')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tenant_id')
        batch_op.drop_column('warehouse_id')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entries_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_branch_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('sync_version')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('source_id')
        batch_op.drop_column('source_module')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('invoice_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('show_payment_method', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('inventory_reservations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_reservations_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_inventory_reservations_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('inventory_cycle_counts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_cycle_counts_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_counts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_counts_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_counts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_counts_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('inventory_cycle_count_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_cycle_count_items_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_count_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_count_items_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_count_items_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_inventory_cycle_count_items_id'))
        batch_op.drop_column('sync_version')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_holidays_tenant_id_tenants'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_holidays_tenant_id'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('grns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grns_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_expense_vouchers_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_expense_vouchers_bank_account_id_bank_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_expense_vouchers_approved_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_expense_vouchers_journal_entry_id_journal_entries'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_expense_vouchers_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('sync_version')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('bank_account_id')
        batch_op.drop_column('journal_entry_id')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_employees_shift_id_shifts'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_employees_username'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))

    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_designations_department_id_departments'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_departments_head_id_employees'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_payments_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_ledger_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_sessions_drawer_id_cash_drawers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cash_sessions_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_cash_sessions_drawer_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('drawer_id')

    with op.batch_alter_table('cash_ledger_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_ledger_entries_journal_entry_id_journal_entries'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cash_ledger_entries_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('camera_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_snapshots_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('branch_devices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_branch_devices_mac_address'), type_='unique')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bank_accounts_account_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_bank_accounts_account_id'), type_='unique')

    with op.batch_alter_table('backup_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('audit_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_sessions_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_items_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_history_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('alert_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_config_pharmacy_id'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('advance_salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_accounts_parent_id_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_accounts_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accounts_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_branch_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))
        batch_op.alter_column('pharmacy_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('sync_version')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('account_type')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
