"""Add enterprise fields and packaging

Revision ID: 5549c987f68b
Revises: 86f743e22366
Create Date: 2026-07-02 15:23:46.289825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5549c987f68b'
down_revision: Union[str, Sequence[str], None] = '86f743e22366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_levels',
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('conversion_qty', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('secondary_barcode', sa.String(length=255), nullable=True),
    sa.Column('is_purchase_unit', sa.Boolean(), nullable=True),
    sa.Column('is_sale_unit', sa.Boolean(), nullable=True),
    sa.Column('is_smallest_unit', sa.Boolean(), nullable=True),
    sa.Column('is_default_pos_unit', sa.Boolean(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packaging_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packaging_levels_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_packaging_levels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packaging_levels_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_packaging_levels_medicine_id'), ['medicine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packaging_levels_secondary_barcode'), ['secondary_barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_packaging_levels_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packaging_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packaging_levels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_packaging_levels_secondary_barcode'))
        batch_op.drop_index(batch_op.f('ix_packaging_levels_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_packaging_levels_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_packaging_levels_id'))
        batch_op.drop_index(batch_op.f('ix_packaging_levels_barcode'))

    op.drop_table('packaging_levels')
    # ### end Alembic commands ###
