"""sync_pharmacy_branches_legacy_id

Revision ID: 6544644a6582
Revises: a0a184e08a94
Create Date: 2026-07-20 12:43:40.000828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6544644a6582'
down_revision: Union[str, Sequence[str], None] = 'a0a184e08a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_accounts_parent_id_accounts'), 'accounts', ['parent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_accounts_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_accounts_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.alter_column('initial_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_batches_expiry_date'))
        batch_op.create_index(batch_op.f('ix_batches_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_batches_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_batches_bin_id_warehouse_bins'), 'warehouse_bins', ['bin_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_batches_rack_id_warehouse_racks'), 'warehouse_racks', ['rack_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_batches_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_branches_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_categories_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_ledger_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_customer_ledger_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_payments_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_customer_payments_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_loyalty_tier'), ['loyalty_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_customers_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_customers_preferred_branch_id_branches'), 'branches', ['preferred_branch_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_departments_head_id_employees'), 'employees', ['head_id'], ['id'])

    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_designations_department_id_departments'), 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_username'), ['username'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_employees_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_employees_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_employees_shift_id_shifts'), 'shifts', ['shift_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_employees_reporting_manager_id_employees'), 'employees', ['reporting_manager_id'], ['id'])

    with op.batch_alter_table('grns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grns_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_grns_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entry_lines_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_journal_entry_lines_branch_id_branches'), 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_journal_entry_lines_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_journal_entry_lines_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_loyalty_transactions_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('base_unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_medicines_internal_product_code'), ['internal_product_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicines_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medicines_sku'), ['sku'], unique=True)
        batch_op.create_index(batch_op.f('ix_medicines_slug'), ['slug'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_medicines_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.drop_column('packaging_unit')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('units_per_pack')

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_payroll_runs_approved_by_users'), 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('pharmacy_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_branches_legacy_branch_id'), ['legacy_branch_id'], unique=False)

    with op.batch_alter_table('po_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_po_items_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_po_items_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_prescription_items_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_prescriptions_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoices_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_purchase_invoices_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_approved_by_users'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_returns_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_purchase_returns_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_purchase_returns_po_id_purchase_orders'), 'purchase_orders', ['po_id'], ['id'])

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_roles_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.drop_column('permissions')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sale_items_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sale_items_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('sale_return_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_return_items_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sale_return_items_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_returns_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sale_returns_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_counter_id_branch_counters'), 'branch_counters', ['counter_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_coupon_id_coupons'), 'coupons', ['coupon_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_shift_id_cash_sessions'), 'cash_sessions', ['shift_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_promotion_id_promotion_campaigns'), 'promotion_campaigns', ['promotion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_salesperson_id_users'), 'users', ['salesperson_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sales_journal_entry_id_journal_entries'), 'journal_entries', ['journal_entry_id'], ['id'])

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_adjustments_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_stock_adjustments_approved_by_users'), 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_adjustments_bin_id_warehouse_bins'), 'warehouse_bins', ['bin_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_adjustments_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_adjustments_rack_id_warehouse_racks'), 'warehouse_racks', ['rack_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_adjustments_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_reference_transfer_id_stock_transfers'), 'stock_transfers', ['reference_transfer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_created_by_users'), 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_warehouse_id_branch_warehouses'), 'branch_warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_rack_id_warehouse_racks'), 'warehouse_racks', ['rack_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_reference_branch_id_branches'), 'branches', ['reference_branch_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_stock_movements_bin_id_warehouse_bins'), 'warehouse_bins', ['bin_id'], ['id'])

    with op.batch_alter_table('supplier_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_ledger_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_supplier_ledger_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_payments_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_supplier_payments_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_suppliers_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_tenants_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('user_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_branches_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_user_branches_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_users_pharmacy_id_pharmacies'), 'pharmacies', ['pharmacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_pharmacy_id'))

    with op.batch_alter_table('user_branches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_branches_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_branches_pharmacy_id'))

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tenants_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tenants_pharmacy_id'))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_suppliers_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suppliers_pharmacy_id'))

    with op.batch_alter_table('supplier_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplier_payments_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supplier_payments_pharmacy_id'))

    with op.batch_alter_table('supplier_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplier_ledger_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supplier_ledger_pharmacy_id'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_bin_id_warehouse_bins'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_reference_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_rack_id_warehouse_racks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_created_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_movements_reference_transfer_id_stock_transfers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_movements_pharmacy_id'))

    with op.batch_alter_table('stock_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stock_adjustments_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_adjustments_rack_id_warehouse_racks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_adjustments_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_adjustments_bin_id_warehouse_bins'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_stock_adjustments_approved_by_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_adjustments_pharmacy_id'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_journal_entry_id_journal_entries'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_salesperson_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_promotion_id_promotion_campaigns'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_shift_id_cash_sessions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_coupon_id_coupons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sales_counter_id_branch_counters'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_pharmacy_id'))

    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_returns_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sale_returns_pharmacy_id'))

    with op.batch_alter_table('sale_return_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_return_items_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sale_return_items_pharmacy_id'))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sale_items_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sale_items_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sale_items_pharmacy_id'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_roles_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_roles_pharmacy_id'))

    with op.batch_alter_table('purchase_returns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_returns_po_id_purchase_orders'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_purchase_returns_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_returns_pharmacy_id'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_approved_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_orders_pharmacy_id'))

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_invoices_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_invoices_pharmacy_id'))

    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_prescriptions_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prescriptions_pharmacy_id'))

    with op.batch_alter_table('prescription_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_prescription_items_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_prescription_items_pharmacy_id'))

    with op.batch_alter_table('po_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_po_items_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_po_items_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_po_items_pharmacy_id'))

    with op.batch_alter_table('pharmacy_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_branches_legacy_branch_id'))

    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payroll_runs_approved_by_users'), type_='foreignkey')

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('units_per_pack', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('packaging_unit', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_medicines_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medicines_slug'))
        batch_op.drop_index(batch_op.f('ix_medicines_sku'))
        batch_op.drop_index(batch_op.f('ix_medicines_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_medicines_internal_product_code'))
        batch_op.alter_column('base_unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_loyalty_transactions_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_pharmacy_id'))

    with op.batch_alter_table('journal_entry_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entry_lines_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entry_lines_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entry_lines_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_journal_entry_lines_id'))

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entries_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_branch_id'))

    with op.batch_alter_table('grns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_grns_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_grns_pharmacy_id'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employees_reporting_manager_id_employees'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_employees_shift_id_shifts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_employees_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_employees_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employees_username'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))

    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_designations_department_id_departments'), type_='foreignkey')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_departments_head_id_employees'), type_='foreignkey')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customers_preferred_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_customers_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_customers_loyalty_tier'))

    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customer_payments_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_payments_pharmacy_id'))

    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customer_ledger_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_ledger_pharmacy_id'))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categories_pharmacy_id'))

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_branches_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_branches_pharmacy_id'))

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_batches_warehouse_id_branch_warehouses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_batches_rack_id_warehouse_racks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_batches_bin_id_warehouse_bins'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_batches_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_batches_pharmacy_id'))
        batch_op.create_index(batch_op.f('ix_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.alter_column('initial_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_accounts_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_accounts_pharmacy_id_pharmacies'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_accounts_parent_id_accounts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accounts_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_accounts_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_branch_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))

    op.create_table('audit_logs',
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('branch_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('previous_value', sqlite.JSON(), nullable=True),
    sa.Column('new_value', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('sync_version', sa.DATETIME(), nullable=True),
    sa.Column('whatsapp_alert_sent', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('media_urls', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    # ### end Alembic commands ###
