"""Add cash register

Revision ID: 86f743e22366
Revises: c8559986a99a
Create Date: 2026-06-22 15:41:15.431958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f743e22366'
down_revision: Union[str, Sequence[str], None] = 'c8559986a99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_return_items', 'sale_return_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sale_return_items', 'sale_item_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sale_return_items', 'medicine_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sale_return_items', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sale_return_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_sale_return_items_id'), 'sale_return_items', ['id'], unique=False)
    op.create_index(op.f('ix_sale_return_items_is_deleted'), 'sale_return_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sale_return_items_tenant_id'), 'sale_return_items', ['tenant_id'], unique=False)
    op.drop_column('sale_return_items', 'branch_id')
    op.create_foreign_key(None, 'sale_returns', 'users', ['cashier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_returns', type_='foreignkey')
    op.add_column('sale_return_items', sa.Column('branch_id', sa.VARCHAR(length=36), nullable=True))
    op.drop_index(op.f('ix_sale_return_items_tenant_id'), table_name='sale_return_items')
    op.drop_index(op.f('ix_sale_return_items_is_deleted'), table_name='sale_return_items')
    op.drop_index(op.f('ix_sale_return_items_id'), table_name='sale_return_items')
    op.alter_column('sale_return_items', 'tenant_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sale_return_items', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('sale_return_items', 'medicine_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sale_return_items', 'sale_item_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('sale_return_items', 'sale_return_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
