"""sales_updates

Revision ID: 9ef97847255c
Revises: 1e78194f4baa
Create Date: 2026-06-20 16:40:08.965492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef97847255c'
down_revision: Union[str, Sequence[str], None] = '1e78194f4baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_ledger',
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_ledger_id'), 'customer_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_customer_ledger_is_deleted'), 'customer_ledger', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customer_ledger_tenant_id'), 'customer_ledger', ['tenant_id'], unique=False)
    op.create_table('customer_payments',
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('sale_id', sa.String(length=36), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_payments_id'), 'customer_payments', ['id'], unique=False)
    op.create_index(op.f('ix_customer_payments_is_deleted'), 'customer_payments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customer_payments_tenant_id'), 'customer_payments', ['tenant_id'], unique=False)
    op.create_table('sale_returns',
    sa.Column('return_number', sa.String(length=100), nullable=True),
    sa.Column('sale_id', sa.String(length=36), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('branch_id', sa.String(length=36), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_version', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_returns_id'), 'sale_returns', ['id'], unique=False)
    op.create_index(op.f('ix_sale_returns_is_deleted'), 'sale_returns', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sale_returns_return_number'), 'sale_returns', ['return_number'], unique=True)
    op.create_index(op.f('ix_sale_returns_tenant_id'), 'sale_returns', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_returns_tenant_id'), table_name='sale_returns')
    op.drop_index(op.f('ix_sale_returns_return_number'), table_name='sale_returns')
    op.drop_index(op.f('ix_sale_returns_is_deleted'), table_name='sale_returns')
    op.drop_index(op.f('ix_sale_returns_id'), table_name='sale_returns')
    op.drop_table('sale_returns')
    op.drop_index(op.f('ix_customer_payments_tenant_id'), table_name='customer_payments')
    op.drop_index(op.f('ix_customer_payments_is_deleted'), table_name='customer_payments')
    op.drop_index(op.f('ix_customer_payments_id'), table_name='customer_payments')
    op.drop_table('customer_payments')
    op.drop_index(op.f('ix_customer_ledger_tenant_id'), table_name='customer_ledger')
    op.drop_index(op.f('ix_customer_ledger_is_deleted'), table_name='customer_ledger')
    op.drop_index(op.f('ix_customer_ledger_id'), table_name='customer_ledger')
    op.drop_table('customer_ledger')
    # ### end Alembic commands ###
