"""add_scope_fields_to_enterprise_roles

Revision ID: 9fd161bdcc63
Revises: 5cec51a58f06
Create Date: 2026-07-15 20:11:16.420386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fd161bdcc63'
down_revision: Union[str, Sequence[str], None] = '5cec51a58f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_customers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('marketing_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('anniversary', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_visit', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lifetime_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_basket', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_returns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_loyalty_tier'), ['loyalty_tier'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_customers_preferred_branch_id_branches'), 'branches', ['preferred_branch_id'], ['id'])

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employee_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reporting_manager_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('employment_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('salary_grade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_account', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('biometric_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('signature', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_employees_reporting_manager_id_employees'), 'employees', ['reporting_manager_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_employees_branch_id_branches'), 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('enterprise_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_scope', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_scope', sa.String(length=50), nullable=True))

    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        pass  # FK to tenants has no name and cannot be dropped safely in SQLite

    with op.batch_alter_table('gift_vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partial_usage_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('redemption_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attachment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('leave_balance', sa.JSON(), nullable=True))

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))

    with op.batch_alter_table('payroll_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonuses', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('incentives', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('provident_fund', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bank_reference', sa.String(), nullable=True))

    with op.batch_alter_table('petty_cash_categories', schema=None) as batch_op:
        pass  # FK to tenants has no name and cannot be dropped safely in SQLite

    with op.batch_alter_table('promotion_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_customer_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('target_loyalty_tier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_segment_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_promotion_campaigns_target_customer_id_customers'), 'customers', ['target_customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_promotion_campaigns_target_customer_id_customers'), type_='foreignkey')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('target_segment_id')
        batch_op.drop_column('target_loyalty_tier')
        batch_op.drop_column('target_customer_id')

    with op.batch_alter_table('petty_cash_categories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('payroll_lines', schema=None) as batch_op:
        batch_op.drop_column('bank_reference')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('provident_fund')
        batch_op.drop_column('tax')
        batch_op.drop_column('incentives')
        batch_op.drop_column('bonuses')
        batch_op.drop_column('overtime')

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('leave_balance')
        batch_op.drop_column('attachment')
        batch_op.drop_column('approval_status')

    with op.batch_alter_table('gift_vouchers', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('redemption_history')
        batch_op.drop_column('partial_usage_allowed')

    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('enterprise_roles', schema=None) as batch_op:
        batch_op.drop_column('data_scope')
        batch_op.drop_column('branch_scope')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employees_branch_id_branches'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_employees_reporting_manager_id_employees'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_column('signature')
        batch_op.drop_column('photo')
        batch_op.drop_column('biometric_id')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('bank_account')
        batch_op.drop_column('salary_grade')
        batch_op.drop_column('employment_type')
        batch_op.drop_column('reporting_manager_id')
        batch_op.drop_column('employee_code')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customers_preferred_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_loyalty_tier'))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('total_returns')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('average_basket')
        batch_op.drop_column('lifetime_value')
        batch_op.drop_column('last_visit')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('occupation')
        batch_op.drop_column('anniversary')
        batch_op.drop_column('sms_opt_in')
        batch_op.drop_column('email_opt_in')
        batch_op.drop_column('whatsapp_opt_in')
        batch_op.drop_column('marketing_opt_in')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferred_branch_id')

    op.create_table('_alembic_tmp_customers',
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('cnic', sa.VARCHAR(length=50), nullable=True),
    sa.Column('whatsapp', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('blood_group', sa.VARCHAR(length=10), nullable=True),
    sa.Column('medical_history', sa.TEXT(), nullable=True),
    sa.Column('allergies', sa.TEXT(), nullable=True),
    sa.Column('credit_limit', sa.FLOAT(), nullable=True),
    sa.Column('current_balance', sa.FLOAT(), nullable=True),
    sa.Column('loyalty_points', sa.INTEGER(), nullable=True),
    sa.Column('loyalty_tier', sa.VARCHAR(length=50), nullable=True),
    sa.Column('area_zone', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('sync_version', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('pharmacy_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('preferred_branch_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=50), nullable=True),
    sa.Column('marketing_opt_in', sa.BOOLEAN(), nullable=True),
    sa.Column('whatsapp_opt_in', sa.BOOLEAN(), nullable=True),
    sa.Column('email_opt_in', sa.BOOLEAN(), nullable=True),
    sa.Column('sms_opt_in', sa.BOOLEAN(), nullable=True),
    sa.Column('anniversary', sa.DATE(), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('last_visit', sa.DATETIME(), nullable=True),
    sa.Column('lifetime_value', sa.FLOAT(), nullable=True),
    sa.Column('average_basket', sa.FLOAT(), nullable=True),
    sa.Column('total_orders', sa.INTEGER(), nullable=True),
    sa.Column('total_returns', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['preferred_branch_id'], ['branches.id'], name=op.f('fk_customers_preferred_branch_id_branches')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
