"""Phase 9 CRM

Revision ID: cb9335adb4be
Revises: 37cada3371bd
Create Date: 2026-07-15 16:28:24.687403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9335adb4be'
down_revision: Union[str, Sequence[str], None] = '37cada3371bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stacking_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('max_usage_per_customer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_branch_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('marketing_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_opt_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('anniversary', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_visit', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lifetime_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_basket', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_returns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_loyalty_tier'), ['loyalty_tier'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_customers_preferred_branch_id_branches'), 'branches', ['preferred_branch_id'], ['id'])



    with op.batch_alter_table('gift_vouchers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partial_usage_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('redemption_history', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))



    with op.batch_alter_table('promotion_campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_customer_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('target_loyalty_tier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_segment_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_promotion_campaigns_target_customer_id_customers'), 'customers', ['target_customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_campaigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_promotion_campaigns_target_customer_id_customers'), type_='foreignkey')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('target_segment_id')
        batch_op.drop_column('target_loyalty_tier')
        batch_op.drop_column('target_customer_id')

    with op.batch_alter_table('petty_cash_categories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('gift_vouchers', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('redemption_history')
        batch_op.drop_column('partial_usage_allowed')

    with op.batch_alter_table('expense_vouchers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_customers_preferred_branch_id_branches'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_loyalty_tier'))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('total_returns')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('average_basket')
        batch_op.drop_column('lifetime_value')
        batch_op.drop_column('last_visit')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('occupation')
        batch_op.drop_column('anniversary')
        batch_op.drop_column('sms_opt_in')
        batch_op.drop_column('email_opt_in')
        batch_op.drop_column('whatsapp_opt_in')
        batch_op.drop_column('marketing_opt_in')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferred_branch_id')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('max_usage_per_customer')
        batch_op.drop_column('stacking_rules')

    # ### end Alembic commands ###
