-- Migration: Apply Multi-Tenant RLS Policies across all tables
-- Autogenerated

-- 1. Check if the current user is a Super Admin
CREATE OR REPLACE FUNCTION current_user_is_super_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM super_admins 
    WHERE auth_user_id = auth.uid() AND is_active = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 2. Get the Pharmacy ID for the current user
CREATE OR REPLACE FUNCTION current_user_pharmacy_id()
RETURNS uuid AS $$
BEGIN
  RETURN (
    SELECT pharmacy_id FROM staff_roles 
    WHERE user_id = auth.uid() 
    LIMIT 1
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- ==========================================
-- Policies for table: tenants
-- ==========================================
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for tenants (ALL)" ON tenants
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for tenants (INSERT)" ON tenants
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: permissions
-- ==========================================
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for permissions (ALL)" ON permissions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for permissions (INSERT)" ON permissions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: roles
-- ==========================================
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for roles (ALL)" ON roles
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for roles (INSERT)" ON roles
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: categories
-- ==========================================
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for categories (ALL)" ON categories
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for categories (INSERT)" ON categories
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: suppliers
-- ==========================================
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for suppliers (ALL)" ON suppliers
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for suppliers (INSERT)" ON suppliers
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: customers
-- ==========================================
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for customers (ALL)" ON customers
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for customers (INSERT)" ON customers
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_generics
-- ==========================================
ALTER TABLE master_generics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_generics (ALL)" ON master_generics
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_generics (INSERT)" ON master_generics
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_brands
-- ==========================================
ALTER TABLE master_brands ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_brands (ALL)" ON master_brands
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_brands (INSERT)" ON master_brands
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_categories
-- ==========================================
ALTER TABLE master_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_categories (ALL)" ON master_categories
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_categories (INSERT)" ON master_categories
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_manufacturers
-- ==========================================
ALTER TABLE master_manufacturers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_manufacturers (ALL)" ON master_manufacturers
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_manufacturers (INSERT)" ON master_manufacturers
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_dosage_forms
-- ==========================================
ALTER TABLE master_dosage_forms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_dosage_forms (ALL)" ON master_dosage_forms
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_dosage_forms (INSERT)" ON master_dosage_forms
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_strengths
-- ==========================================
ALTER TABLE master_strengths ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_strengths (ALL)" ON master_strengths
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_strengths (INSERT)" ON master_strengths
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_strength_units
-- ==========================================
ALTER TABLE master_strength_units ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_strength_units (ALL)" ON master_strength_units
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_strength_units (INSERT)" ON master_strength_units
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_routes
-- ==========================================
ALTER TABLE master_routes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_routes (ALL)" ON master_routes
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_routes (INSERT)" ON master_routes
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_storage_conditions
-- ==========================================
ALTER TABLE master_storage_conditions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_storage_conditions (ALL)" ON master_storage_conditions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_storage_conditions (INSERT)" ON master_storage_conditions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_tax_rules
-- ==========================================
ALTER TABLE master_tax_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_tax_rules (ALL)" ON master_tax_rules
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_tax_rules (INSERT)" ON master_tax_rules
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_packaging
-- ==========================================
ALTER TABLE master_packaging ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_packaging (ALL)" ON master_packaging
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_packaging (INSERT)" ON master_packaging
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_units
-- ==========================================
ALTER TABLE master_units ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_units (ALL)" ON master_units
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_units (INSERT)" ON master_units
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_prescription_types
-- ==========================================
ALTER TABLE master_prescription_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_prescription_types (ALL)" ON master_prescription_types
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_prescription_types (INSERT)" ON master_prescription_types
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_flavors
-- ==========================================
ALTER TABLE master_flavors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_flavors (ALL)" ON master_flavors
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_flavors (INSERT)" ON master_flavors
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_age_groups
-- ==========================================
ALTER TABLE master_age_groups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_age_groups (ALL)" ON master_age_groups
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_age_groups (INSERT)" ON master_age_groups
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_warehouses
-- ==========================================
ALTER TABLE master_warehouses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_warehouses (ALL)" ON master_warehouses
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_warehouses (INSERT)" ON master_warehouses
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_racks
-- ==========================================
ALTER TABLE master_racks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_racks (ALL)" ON master_racks
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_racks (INSERT)" ON master_racks
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_shelves
-- ==========================================
ALTER TABLE master_shelves ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_shelves (ALL)" ON master_shelves
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_shelves (INSERT)" ON master_shelves
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_bins
-- ==========================================
ALTER TABLE master_bins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_bins (ALL)" ON master_bins
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_bins (INSERT)" ON master_bins
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: master_suppliers
-- ==========================================
ALTER TABLE master_suppliers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for master_suppliers (ALL)" ON master_suppliers
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for master_suppliers (INSERT)" ON master_suppliers
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: branches
-- ==========================================
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for branches (ALL)" ON branches
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for branches (INSERT)" ON branches
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: role_permissions
-- ==========================================
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for role_permissions (ALL)" ON role_permissions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for role_permissions (INSERT)" ON role_permissions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: users
-- ==========================================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for users (ALL)" ON users
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for users (INSERT)" ON users
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicines
-- ==========================================
ALTER TABLE medicines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicines (ALL)" ON medicines
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicines (INSERT)" ON medicines
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: prescriptions
-- ==========================================
ALTER TABLE prescriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for prescriptions (ALL)" ON prescriptions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for prescriptions (INSERT)" ON prescriptions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: accounts
-- ==========================================
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for accounts (ALL)" ON accounts
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for accounts (INSERT)" ON accounts
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: departments
-- ==========================================
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for departments (ALL)" ON departments
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for departments (INSERT)" ON departments
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: designations
-- ==========================================
ALTER TABLE designations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for designations (ALL)" ON designations
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for designations (INSERT)" ON designations
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: shifts
-- ==========================================
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for shifts (ALL)" ON shifts
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for shifts (INSERT)" ON shifts
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: tenant_settings
-- ==========================================
ALTER TABLE tenant_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for tenant_settings (ALL)" ON tenant_settings
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for tenant_settings (INSERT)" ON tenant_settings
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: invoice_settings
-- ==========================================
ALTER TABLE invoice_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for invoice_settings (ALL)" ON invoice_settings
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for invoice_settings (INSERT)" ON invoice_settings
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: system_modules
-- ==========================================
ALTER TABLE system_modules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for system_modules (ALL)" ON system_modules
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for system_modules (INSERT)" ON system_modules
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: ocr_queues
-- ==========================================
ALTER TABLE ocr_queues ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for ocr_queues (ALL)" ON ocr_queues
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for ocr_queues (INSERT)" ON ocr_queues
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_master
-- ==========================================
ALTER TABLE medicine_master ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_master (ALL)" ON medicine_master
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_master (INSERT)" ON medicine_master
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_templates
-- ==========================================
ALTER TABLE medicine_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_templates (ALL)" ON medicine_templates
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_templates (INSERT)" ON medicine_templates
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: user_branches
-- ==========================================
ALTER TABLE user_branches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for user_branches (ALL)" ON user_branches
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for user_branches (INSERT)" ON user_branches
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_substitutes
-- ==========================================
ALTER TABLE medicine_substitutes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_substitutes (ALL)" ON medicine_substitutes
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_substitutes (INSERT)" ON medicine_substitutes
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: batches
-- ==========================================
ALTER TABLE batches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for batches (ALL)" ON batches
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for batches (INSERT)" ON batches
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: audit_sessions
-- ==========================================
ALTER TABLE audit_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for audit_sessions (ALL)" ON audit_sessions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for audit_sessions (INSERT)" ON audit_sessions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: packaging_levels
-- ==========================================
ALTER TABLE packaging_levels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for packaging_levels (ALL)" ON packaging_levels
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for packaging_levels (INSERT)" ON packaging_levels
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: purchase_orders
-- ==========================================
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for purchase_orders (ALL)" ON purchase_orders
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for purchase_orders (INSERT)" ON purchase_orders
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: supplier_ledger
-- ==========================================
ALTER TABLE supplier_ledger ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for supplier_ledger (ALL)" ON supplier_ledger
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for supplier_ledger (INSERT)" ON supplier_ledger
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: supplier_medicine_prices
-- ==========================================
ALTER TABLE supplier_medicine_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for supplier_medicine_prices (ALL)" ON supplier_medicine_prices
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for supplier_medicine_prices (INSERT)" ON supplier_medicine_prices
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: prescription_items
-- ==========================================
ALTER TABLE prescription_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for prescription_items (ALL)" ON prescription_items
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for prescription_items (INSERT)" ON prescription_items
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: sales
-- ==========================================
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for sales (ALL)" ON sales
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for sales (INSERT)" ON sales
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: customer_ledger
-- ==========================================
ALTER TABLE customer_ledger ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for customer_ledger (ALL)" ON customer_ledger
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for customer_ledger (INSERT)" ON customer_ledger
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: journal_entries
-- ==========================================
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for journal_entries (ALL)" ON journal_entries
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for journal_entries (INSERT)" ON journal_entries
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: employees
-- ==========================================
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for employees (ALL)" ON employees
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for employees (INSERT)" ON employees
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: payroll_runs
-- ==========================================
ALTER TABLE payroll_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for payroll_runs (ALL)" ON payroll_runs
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for payroll_runs (INSERT)" ON payroll_runs
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: notifications
-- ==========================================
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for notifications (ALL)" ON notifications
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for notifications (INSERT)" ON notifications
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: backup_history
-- ==========================================
ALTER TABLE backup_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for backup_history (ALL)" ON backup_history
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for backup_history (INSERT)" ON backup_history
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: cash_sessions
-- ==========================================
ALTER TABLE cash_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for cash_sessions (ALL)" ON cash_sessions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for cash_sessions (INSERT)" ON cash_sessions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_packaging
-- ==========================================
ALTER TABLE medicine_packaging ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_packaging (ALL)" ON medicine_packaging
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_packaging (INSERT)" ON medicine_packaging
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_pricing
-- ==========================================
ALTER TABLE medicine_pricing ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_pricing (ALL)" ON medicine_pricing
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_pricing (INSERT)" ON medicine_pricing
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_supplier_mapping
-- ==========================================
ALTER TABLE medicine_supplier_mapping ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_supplier_mapping (ALL)" ON medicine_supplier_mapping
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_supplier_mapping (INSERT)" ON medicine_supplier_mapping
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_images
-- ==========================================
ALTER TABLE medicine_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_images (ALL)" ON medicine_images
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_images (INSERT)" ON medicine_images
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_documents
-- ==========================================
ALTER TABLE medicine_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_documents (ALL)" ON medicine_documents
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_documents (INSERT)" ON medicine_documents
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_audit_logs
-- ==========================================
ALTER TABLE medicine_audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_audit_logs (ALL)" ON medicine_audit_logs
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_audit_logs (INSERT)" ON medicine_audit_logs
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_versions
-- ==========================================
ALTER TABLE medicine_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_versions (ALL)" ON medicine_versions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_versions (INSERT)" ON medicine_versions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_custom_fields
-- ==========================================
ALTER TABLE medicine_custom_fields ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_custom_fields (ALL)" ON medicine_custom_fields
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_custom_fields (INSERT)" ON medicine_custom_fields
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_ai_tags
-- ==========================================
ALTER TABLE medicine_ai_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_ai_tags (ALL)" ON medicine_ai_tags
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_ai_tags (INSERT)" ON medicine_ai_tags
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: stock_adjustments
-- ==========================================
ALTER TABLE stock_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for stock_adjustments (ALL)" ON stock_adjustments
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for stock_adjustments (INSERT)" ON stock_adjustments
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: stock_movements
-- ==========================================
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for stock_movements (ALL)" ON stock_movements
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for stock_movements (INSERT)" ON stock_movements
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: audit_items
-- ==========================================
ALTER TABLE audit_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for audit_items (ALL)" ON audit_items
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for audit_items (INSERT)" ON audit_items
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: po_items
-- ==========================================
ALTER TABLE po_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for po_items (ALL)" ON po_items
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for po_items (INSERT)" ON po_items
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: grns
-- ==========================================
ALTER TABLE grns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for grns (ALL)" ON grns
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for grns (INSERT)" ON grns
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: loyalty_transactions
-- ==========================================
ALTER TABLE loyalty_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for loyalty_transactions (ALL)" ON loyalty_transactions
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for loyalty_transactions (INSERT)" ON loyalty_transactions
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: sale_items
-- ==========================================
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for sale_items (ALL)" ON sale_items
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for sale_items (INSERT)" ON sale_items
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: sale_returns
-- ==========================================
ALTER TABLE sale_returns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for sale_returns (ALL)" ON sale_returns
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for sale_returns (INSERT)" ON sale_returns
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: customer_payments
-- ==========================================
ALTER TABLE customer_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for customer_payments (ALL)" ON customer_payments
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for customer_payments (INSERT)" ON customer_payments
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: journal_entry_lines
-- ==========================================
ALTER TABLE journal_entry_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for journal_entry_lines (ALL)" ON journal_entry_lines
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for journal_entry_lines (INSERT)" ON journal_entry_lines
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: attendance
-- ==========================================
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for attendance (ALL)" ON attendance
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for attendance (INSERT)" ON attendance
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: leave_requests
-- ==========================================
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for leave_requests (ALL)" ON leave_requests
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for leave_requests (INSERT)" ON leave_requests
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: payroll_lines
-- ==========================================
ALTER TABLE payroll_lines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for payroll_lines (ALL)" ON payroll_lines
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for payroll_lines (INSERT)" ON payroll_lines
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: cash_ledger_entries
-- ==========================================
ALTER TABLE cash_ledger_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for cash_ledger_entries (ALL)" ON cash_ledger_entries
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for cash_ledger_entries (INSERT)" ON cash_ledger_entries
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_conversion_rules
-- ==========================================
ALTER TABLE medicine_conversion_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_conversion_rules (ALL)" ON medicine_conversion_rules
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_conversion_rules (INSERT)" ON medicine_conversion_rules
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: medicine_barcodes
-- ==========================================
ALTER TABLE medicine_barcodes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for medicine_barcodes (ALL)" ON medicine_barcodes
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for medicine_barcodes (INSERT)" ON medicine_barcodes
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: purchase_invoices
-- ==========================================
ALTER TABLE purchase_invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for purchase_invoices (ALL)" ON purchase_invoices
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for purchase_invoices (INSERT)" ON purchase_invoices
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: purchase_returns
-- ==========================================
ALTER TABLE purchase_returns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for purchase_returns (ALL)" ON purchase_returns
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for purchase_returns (INSERT)" ON purchase_returns
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: sale_return_items
-- ==========================================
ALTER TABLE sale_return_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for sale_return_items (ALL)" ON sale_return_items
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for sale_return_items (INSERT)" ON sale_return_items
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: supplier_payments
-- ==========================================
ALTER TABLE supplier_payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for supplier_payments (ALL)" ON supplier_payments
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for supplier_payments (INSERT)" ON supplier_payments
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: holidays
-- ==========================================
ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for holidays (ALL)" ON holidays
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for holidays (INSERT)" ON holidays
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: advance_salaries
-- ==========================================
ALTER TABLE advance_salaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for advance_salaries (ALL)" ON advance_salaries
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for advance_salaries (INSERT)" ON advance_salaries
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: payroll_settings
-- ==========================================
ALTER TABLE payroll_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for payroll_settings (ALL)" ON payroll_settings
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for payroll_settings (INSERT)" ON payroll_settings
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: expense_vouchers
-- ==========================================
ALTER TABLE expense_vouchers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for expense_vouchers (ALL)" ON expense_vouchers
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for expense_vouchers (INSERT)" ON expense_vouchers
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: petty_cash_categories
-- ==========================================
ALTER TABLE petty_cash_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for petty_cash_categories (ALL)" ON petty_cash_categories
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for petty_cash_categories (INSERT)" ON petty_cash_categories
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: purchase_return_items
-- ==========================================
ALTER TABLE purchase_return_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for purchase_return_items (ALL)" ON purchase_return_items
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for purchase_return_items (INSERT)" ON purchase_return_items
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: audit_events
-- ==========================================
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for audit_events (SELECT)" ON audit_events
FOR SELECT TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for audit_events (INSERT)" ON audit_events
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: alert_history
-- ==========================================
ALTER TABLE alert_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for alert_history (ALL)" ON alert_history
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for alert_history (INSERT)" ON alert_history
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: camera_snapshots
-- ==========================================
ALTER TABLE camera_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for camera_snapshots (SELECT)" ON camera_snapshots
FOR SELECT TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for camera_snapshots (INSERT)" ON camera_snapshots
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: alert_config
-- ==========================================
ALTER TABLE alert_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for alert_config (ALL)" ON alert_config
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for alert_config (INSERT)" ON alert_config
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: whatsapp_bot_log
-- ==========================================
ALTER TABLE whatsapp_bot_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for whatsapp_bot_log (ALL)" ON whatsapp_bot_log
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for whatsapp_bot_log (INSERT)" ON whatsapp_bot_log
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

-- ==========================================
-- Policies for table: pharmacies
-- ==========================================
ALTER TABLE pharmacies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for pharmacies (ALL)" ON pharmacies
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for pharmacies (INSERT)" ON pharmacies
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin()
);

-- ==========================================
-- Policies for table: super_admins
-- ==========================================
ALTER TABLE super_admins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for super_admins (ALL)" ON super_admins
FOR ALL TO authenticated
USING (current_user_is_super_admin());

CREATE POLICY "Pharmacy isolation for super_admins (INSERT)" ON super_admins
FOR INSERT TO authenticated
WITH CHECK (current_user_is_super_admin());

-- ==========================================
-- Policies for table: staff_roles
-- ==========================================
ALTER TABLE staff_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pharmacy isolation for staff_roles (ALL)" ON staff_roles
FOR ALL TO authenticated
USING (
    current_user_is_super_admin() 
    OR user_id = auth.uid()
    OR pharmacy_id = current_user_pharmacy_id()
);

CREATE POLICY "Pharmacy isolation for staff_roles (INSERT)" ON staff_roles
FOR INSERT TO authenticated
WITH CHECK (
    current_user_is_super_admin() 
    OR pharmacy_id = current_user_pharmacy_id()
);

